#!/usr/bin/env php
<?php

if (file_exists(__DIR__ . "/../.git/hooks/pre-commit")) {
    $PRE_COMMIT_EXISTS=1;
} else {
    $PRE_COMMIT_EXISTS=0;
}

copy(__DIR__ . "/pre-commit", __DIR__ . "/../.git/hooks/pre-commit");
exec("chmod +x \"" . __DIR__ . "/../.git/hooks/pre-commit\"");

if ($PRE_COMMIT_EXISTS === 0) {
    echo "Pre-commit git hook is installed!";
} else {
    echo "Pre-commit git hook is updated!";
}
